Title =  "积木の部落"
LanguageCode = "zh-CN"
BaseUrl = "https://bakakuma.moe/"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "zh"

[Params]
  Introduce = "Geek & Programmer"
  Description = "积木的博客"
  Keywords =  "积木,博客,程序员,个人,笔记,技术,分享"
  Subtitle = '"每个人都是积木盒中的玩具"'
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.png"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  #BaiduStatsId = "0b07433b4ab8d587dae7d34e71973839"
  #QQStatsId = "58416275"
  RevolverMapId = "5b4f2ucxar6"
  Fancybox = true
  copyright = "Wayne Zhao"

[Author]
  Name = "积木盒"

[Params.Share]
  Disqus = "bakakuma"
  Baidu = false

[[Menu.Main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "Technique"
  Pre = "code"
  URL = "/categories/Technique/"
  Weight = 2
[[Menu.Main]]
  Name = "Reflection"
  Pre = "tint"
  URL = "/categories/Reflection/"
  Weight = 3
[[Menu.Main]]
  Name = "Notes"
  Pre = "book"
  URL = "/categories/Notes/"
  Weight = 4
[[Menu.Main]]
  Name = "Routine"
  Pre = "leaf"
  URL = "/categories/Routine/"
  Weight = 5
[[Menu.Main]]
  Name = "Archive"
  Pre = "archive"
  URL = "/categories/Archive/"
  Weight = 6
[[Menu.Main]]
  Name = "About"
  Pre = "user"
  URL = "/about/"
  Weight = 7

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/waynezhao12/"

[[Params.Socials]]
  Name = "Twitter"
  Icon = "twitter"
  URL = "https://twitter.com/Bakakuma12"

[[Params.Socials]]
  Name = "Mastodon"
  Icon = "mastodon"
  URL = "https://nebula.moe/@Bakkumira"

[[Params.Socials]]
  Name = "Steam"
  Icon = "steam"
  URL = "https://steamcommunity.com/id/tsumikihako"
